language: cpp
notifications:
  email: false
sudo: false
dist: trusty
services:
- docker
matrix:
  include:
  - os: linux
    compiler: clang
    env: CXX=clang++ CC=clang
  - os: linux
    compiler: gcc
    env: CXX=g++ CC=gcc
script:
- docker run -e "CI" -e "TRAVIS" -e "TRAVIS_TAG" -e "TRAVIS_BUILD_NUMBER" -e "CXX"
  -e "CC" -e "REPOSITORY_KEY" --tty=false -it -v $PWD:/src --workdir /src bentou/ubuntu-bionic-dev
  python3 ./build.py
before_script:
- docker pull bentou/ubuntu-bionic-dev
- docker ps -a
- mkdir bin
env:
  matrix:
    secure: Y0HOmk9cSFmdBh3+bGyZwN/P03xDokenii9PV0wKbmBZ9KAplMt+Sxg84JUuu7EG9V2COGOK/GooKe6mDZIBjBjJfPFW37YZ+EOPGh+gTEh/mJ1UvuE/6DqbxB1DI8wv38voEZsVDGNutZ8PLJ6HtcHtxksS2eyiwiVXpD/oKcSbCRLd+frSIRN3e4gQk50DpslHk2hYKwxVKC7Lvtrgksk8lIGOAE0Au9YG2bEP0A5WXFlXg71RvTFFwelF8PxkJ5to3zJsujts7BJPDyX6qC2sWkbBnY1fTceTKc7cIDbSWnvMUeEHjcqKDw5K2vaBu3fL3QIf/tKIq+PsMXWIni+pDLTtw/wugYUj3lhq9YjnCJp7Zhcf4ha1LrVmBpwEyqQOWPfbeU8j71j+DYDNUXYy+v9hDmQl6XBCJ2wHe3uoKk1H878Hc3/neouAdNfZRV4dkUahDHolB08+H0vzqcQPA9j3R1zQCV2iRU4y4HcVm2YZg1EVsPAzkkg13PvOKnyf8hrSlAMm6SVPA1wMvoeKIN+Izw5q5ieEkmUXVld7puwDVbLoPQ9nXYNn4EK9i17uYDuuCWtD3FNdBb+JMwA8s1qTqGR4S7+S9M0GGJFWg/iCbDwvePvH+4sO4LeBdBnaFZLwEN1T0EwBCiCc7uSgK92o2M2kLU6miCsJxLA=
